version: '3'
services:
  # hazelcast imdg
  hazelcast:
    image: barisaydinoz/swarm-driver:1.11
    ports:
      - "5701:5701"
    deploy:
    # increase replica size
      replicas: 1
    networks:
      - backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/Users/baris/work/hazelcast-swarm/experimental-driver/experimental-swarm-driver/target/docker/barisaydinoz/swarm-driver/1.3/build/maven:/target"
    # volumes:
    #     - .:/configFolder
    environment:
      - JAVA_OPTS=-Dhazelcast.config=/target/hazelcast.xml

  # visualizer
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

# networks
networks:
  backend:
